language: node_js
node_js:
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"
os:
    - linux
    - osx
matrix:
    exclude:
        - os: osx # skip this because on Travis, node.js segfaults on osx+node 9
          node_js: "9"
cache:
    directories:
        - node_modules
