language: node_js
node_js:
    - "10"
    - "12"
os:
    - linux
    - osx

matrix:
    exclude:
        - os: osx # skip this because on Travis, node.js segfaults on osx+node 11
          node_js: "12"
